server:
  port: 8090

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: SmartGrid-frontend
          uri: http://localhost:8082
          predicates:
            - Path=/index, /css/**, /img/**, /js/**, /

        - id: authservice
          uri: http://localhost:8080
          predicates:
            - Path=/auth/**, /oauth2/**, /login/oauth2/**
