server:
  port: 8090

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: frontend
          uri: http://localhost:8082
          predicates:
            - Path=/login, /validar-cliente, /validar-empleado

        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**, /oauth2/**, /login/oauth2/**
